# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inv.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox_name = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_name.setGeometry(QtCore.QRect(30, 120, 141, 21))
        self.spinBox_name.setObjectName("spinBox_name")
        self.spinBox_unit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_unit.setGeometry(QtCore.QRect(190, 120, 81, 21))
        self.spinBox_unit.setObjectName("spinBox_unit")
        self.spinBox_subunit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_subunit.setGeometry(QtCore.QRect(280, 120, 91, 21))
        self.spinBox_subunit.setObjectName("spinBox_subunit")
        self.lineEdit_kab = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kab.setGeometry(QtCore.QRect(380, 120, 113, 20))
        self.lineEdit_kab.setObjectName("lineEdit_kab")
        self.lineEdit_count = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_count.setGeometry(QtCore.QRect(510, 120, 113, 20))
        self.lineEdit_count.setObjectName("lineEdit_count")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_name.setObjectName("label_name")
        self.label_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_unit.setGeometry(QtCore.QRect(190, 90, 61, 16))
        self.label_unit.setObjectName("label_unit")
        self.label_subunit = QtWidgets.QLabel(self.centralwidget)
        self.label_subunit.setGeometry(QtCore.QRect(280, 90, 91, 16))
        self.label_subunit.setObjectName("label_subunit")
        self.label_kab = QtWidgets.QLabel(self.centralwidget)
        self.label_kab.setGeometry(QtCore.QRect(390, 90, 47, 13))
        self.label_kab.setObjectName("label_kab")
        self.label_count = QtWidgets.QLabel(self.centralwidget)
        self.label_count.setGeometry(QtCore.QRect(520, 90, 61, 16))
        self.label_count.setObjectName("label_count")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_into_values = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_into_values.setGeometry(QtCore.QRect(480, 170, 131, 23))
        self.pushButton_into_values.setObjectName("pushButton_into_values")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Наименование"))
        self.label_unit.setText(_translate("MainWindow", "Отделение"))
        self.label_subunit.setText(_translate("MainWindow", "Подразделение"))
        self.label_kab.setText(_translate("MainWindow", "Кабинет"))
        self.label_count.setText(_translate("MainWindow", "Количество"))
        self.pushButton_clear.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_into_values.setText(_translate("MainWindow", "Внести данные"))
